name: Deploy Discord bot

on:
  schedule:
    #Hora en UTC = Hora local + 5 horas
    - cron: '0 17 * * *'
    - cron: '0 20 * * *'
    - cron: '0 23 * * *'
    - cron: '0 5 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: |
          echo "SERVER_ID=${{ secrets.SERVER_ID }}" > .env
          echo "APP_TOKEN=${{ secrets.APP_TOKEN }}" >> .env
          echo "APP_ID=${{ secrets.APP_ID }}" >> .env
          echo "PREFIX=${{ secrets.PREFIX }}" >> .env

      - name: Run bot for 2 hours
        run: |
          npx ts-node ./src/bot.ts &
          sleep 3600
          kill $!

      - name: Clean up .env file
        run: rm -f .env
