name: Deploy Discord bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SERVER_ID: ${{ secrets.SERVER_ID }}
      APP_TOKEN: ${{ secrets.APP_TOKEN }}
      APP_ID: ${{ secrets.APP_ID }}
      PREFIX: ${{ secrets.PREFIX }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Optional: Fetch all history for all branches (if needed)

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Updated to the latest version
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: |
          echo "SERVER_ID=${{ secrets.SERVER_ID }}" > .env
          echo "APP_TOKEN=${{ secrets.APP_TOKEN }}" >> .env
          echo "APP_ID=${{ secrets.APP_ID }}" >> .env
          echo "PREFIX=${{ secrets.PREFIX }}" >> .env

      - name: Run bot
        run: npx ts-node ./src/bot.ts

      - name: Clean up .env file
        run: rm -f .env
